fixtures:
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      "ref": "5.0.0"
    "translate":
      "repo": "https://github.com/puppetlabs/puppetlabs-translate"
  symlinks:
    "accounts": "#{source_dir}"
