fixtures:
  repositories:
    sshkeys_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-sshkeys_core'
      puppet_version: '>= 6.0.0'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '5.0.0'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:
			repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
			ref: v4.12.1
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    accounts: "#{source_dir}"
