---
  ".gitlab-ci.yml":
    delete: true
  ".rubocop.yml":
    default_configs:
      inherit_from: ".rubocop_todo.yml"
      require:
      - rubocop-i18n
      - rubocop-rspec
  ".travis.yml":
    global_env: 
      - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
    dist: trusty
    deploy_to_forge:
      enabled: false
    use_litmus: true
    litmus:
      provision_list:
        - travis_ub
        - travis_deb
        - travis_el7
    simplecov: true
    user: puppet
    secure: ''
    branches:
    - release
    notifications:
      slack:
        secure: >-
          X5RjXKqWPwT3G1OPSNYywNvioN2iALi6FwaSVc3gBe7GqMpj/rvfGIYOGmzchrQeoEKi/tOmHBiYUisBt23eVWVhGozFqFlYR/Dcy5Zhy1QImr3KMJjwWMWIMfMa8KPPpsBoxpsrzWeMGg8+jfpjwRF6IE+GW9zSXwehEy5ur/e819ztdomY76ZIa6ohTX3TmKlb5P4SCMRfs2SyvoocmsgYvUP/riT4a0VF4JoSPft/d1ePc1WLJDd2SbNuVCUisapzkyY7lKeryMu9Qht6Qdr72awDMfg9/MVy3fHFCvwduSs/idfih41qPyWx7Fr8pmr1CzWRUyBrYEq7FT/4fODz4JoIWHEMfFJA4Og9oxkFPOqCWLV+kWqtGmqrjfi1WTz4S3zufQWrn2fxLpgFzQl+5QnthT4EgEUWsp2AO+toUCPePzvjAb3KJceD4r5QMZIVk55czoWJmMI8DD1PVi8FBKA5H5kp8Hn0i1XWrrlzfgGYMV89J4Vn7m507P7d9szh9SFLVT9RLSOX6N7F04FmMJbxOeyNMwTDschmghhATBiy26dW1cSw4NlgJT6QaSOUi64QQfGSONmsaa6q/VYt4MaVW7oeex3/RFq7EbDRXj1kKaYK6Wl5Vj4eSe7/ve9C6yY+gcPwt025kQ8OPtSX87DKT2IAeG9GqRSypeQ=
  appveyor.yml:
    delete: true
  Gemfile:
    optional:
      ":development":
      - gem: github_changelog_generator
        git: https://github.com/skywinder/github-changelog-generator
        ref: 20ee04ba1234e9e83eb2ffb5056e23d641c7a018
        condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')
    required:
      ":development":
      - gem: puppet-lint-i18n
  Rakefile:
    requires:
    - puppet_pot_generator/rake_tasks
  spec/spec_helper.rb:
    mock_with: ":rspec"
    coverage_report: true
